name: Update Github Repo Settings

on:
  push:
    paths:
      - '.github/actions/update-github-repo-settings.js'
      - '.github/workflows/github-settings.yml'

jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: . .github/actions/update-github-repo-settings.sh
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
