name: Update Github Repo Settings

on:
  push:
    paths:
      - '.github/actions/update-github-repo-settings.js'
      - '.github/workflows/github-settings.yml'

jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -u raboley:${{ secrets.API_GITHUB_TOKEN }} \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{"delete_branch_on_merge":"true"}'
