name: publish docs

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ruby-version: 2.5

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: install go-slate
        run: go get -u github.com/growler/go-slate

      - name: build docs
        run: go-slate site docs/ build/

      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build