name: Terraform
# This workflow is triggered on pushes to the repository.
on: pull_request

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set pull_number var to tfvars & tf backend
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo 'suffix = "review-'$pull_number'"' > env.auto.tfvars

          cat env.auto.tfvars
        working-directory: terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Create Terraform Backend
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo 'workspaces { name = "review-infrastructure-main-review-'$pull_number'" }
                hostname     = "app.terraform.io"
                organization = "russellboley"' > terraform/backend.hcl

          cat terraform/backend.hcl

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl
        working-directory: terraform

      - name: Set Terraform Cloud backend Exectuion to local
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          export TERRAFORM_CLOUD_WORKSPACE_NAME="review-infrastructure-review-$pull_number"
          . scripts/terraform_cloud_set_workspace_execution_local.sh
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TERRAFORM_CLOUD_ORG_NAME: russellboley

      - name: Terraform apply
        run: terraform apply --auto-approve
        working-directory: terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}


